# Generated by Django 4.0.1 on 2022-01-25 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driverinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(default='', max_length=10)),
                ('max_passengers', models.PositiveIntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('TRUCK', 'TRUCK'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER')], default='SEDAN', max_length=10)),
                ('special_info', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
