# Generated by Django 4.0.1 on 2022-01-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='licence',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_passengers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('TRUCK', 'TRUCK'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER')], default='SEDAN', max_length=10),
        ),
        migrations.DeleteModel(
            name='Driverinfo',
        ),
    ]
