# Generated by Django 4.0.1 on 2022-01-25 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile_licence_profile_max_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='licence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='special_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vehicle_type',
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(default='', max_length=10)),
                ('max_passengers', models.PositiveIntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('TRUCK', 'TRUCK'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER')], default='SEDAN', max_length=10)),
                ('special_info', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
