# Generated by Django 4.0.1 on 2022-01-28 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('TRUCK', 'TRUCK'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER')], max_length=10)),
                ('can_be_shared', models.BooleanField()),
                ('special_requests', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ride_driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_onwer', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
