# Generated by Django 4.0.1 on 2022-01-30 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_time', models.DateTimeField()),
                ('late_time', models.DateTimeField()),
                ('num_people', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Format: 2022-01-28 12:00')),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('num_sharers', models.PositiveIntegerField(default=0)),
                ('num_all', models.PositiveIntegerField(default=0)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SEDAN', 'SEDAN'), ('COMPACT', 'COMPACT'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('TRUCK', 'TRUCK'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER')], max_length=10)),
                ('can_be_shared', models.BooleanField()),
                ('is_open', models.BooleanField(default=True)),
                ('special_requests', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ride_driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(related_name='ride_sharer', through='rides.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
