# Generated by Django 4.0.1 on 2022-01-28 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_ride_is_open_ride_num_all_alter_ride_sharer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(help_text='Format: 2022-01-28 12:00'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, default=None, related_name='ride_sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
